// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
use uuid::Uuid;
#[derive(Queryable, Debug)]
pub struct Client {
    pub id: Uuid,
    pub redirect_uri_id: i32,
    pub default_scope: Option<Vec<String>>,
    pub client_type: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct RegisteredUrl {
    pub id: i32,
    pub client_id: Option<Uuid>,
    pub url: String,
    pub type_: i16,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

