[workspace]
members = [
  "empty-utils",
  "empty-oauth",
  "empty-blog",
]



[workspace.dependencies]

# common
tokio = { version = "1.25", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0"
lazy_static ="1.4"
log = "0.4"
tracing="0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
rand = "0.8.4"

# database
diesel = { version = "2.0", features = ["postgres", "r2d2", "chrono", "uuid"] }
chrono = { version = "0.4", features = ["serde"] }
uuid= { version = "1.3", features = ["serde", "v4"] }
dotenvy = "0.15"
diesel_cli_ext="0.3"


# rustful
axum = { version = "0.6", features = ["http2"] }
utoipa = {version = "3.0", features = ["axum_extras", "yaml"] }
utoipa-swagger-ui ={version =  "3.0", features = ["axum"] }
tower-http="*"
oxide-auth = "*"
oxide-auth-axum = "*"

empty-utils = {path = "empty-utils"}
# empty-macro = { path="empty-macro" }

#empty-oauth
url="*"
