openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
  description: 接口文档
servers:
  - url: https://api.server.test/v1

tags:
  - name: question

paths:
  /questions:
    get:
      tags:
        - question
      description: 获取题目
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
    post:
      tags:
       - question
      description: 新增题目
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        200:
          description: ok
  /questions/{id}:
    get:
      tags:
        - question
      description: 获取一道题
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
    put:
      tags:
        - question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        200:
          description: ok
    delete:
      tags:
        - question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        200:
          description: ok
  /questions/{id}/answers/:
    get:
      tags:
        - question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
    post:
      tags:
        - question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/Answer'
      responses:
        200:
          description: ok
    patch:
      tags:
        - question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/Answer'
      responses:
        200:
          description: ok
  /questions/{id}/answers/{answerId}:
    put:
      tags:
        - question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
        - name: answerId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Answer'
      responses:
        200:
          description: ok

components:
  schemas:
    ID: 
      type: integer
    Question:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ID'
        question:
          type: string
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
        answerIds:
          type: array
          items:
            type: integer

    Answer:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ID'
        content:
          type: string
