[package]
name = "empty-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "*"
diesel = "*"
chrono = { version = "*" }
prost-types = "*"
log = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
dotenvy ="*"
clap = { version = "4.1", features = ["derive"] }
walkdir = "2.3"
cargo_toml = "0.15"
toml = "0.7.2"

[[bin]]
name = "cli"

