[package]
name = "empty-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "*"
diesel = "*"
chrono = { version = "*" }
prost-types = "*"
log = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
dotenvy ="*"