// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
use uuid::Uuid;
#[derive(Queryable, Debug)]
pub struct Answer {
    pub id: i32,
    pub question_id: i32,
    pub content: String,
    pub correct: bool,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct ClientScope {
    pub id: i32,
    pub client_id: Uuid,
    pub redirect_uri_id: i32,
    pub created_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Client {
    pub id: Uuid,
    pub redirect_uri_id: i32,
    pub name: String,
    pub desc: String,
    pub passphrase: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Question {
    pub id: i32,
    pub content: String,
    pub desc: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct RedirectUri {
    pub id: i32,
    pub url: String,
    pub created_at: NaiveDateTime,
    pub client_id: Option<Uuid>,
}

#[derive(Queryable, Debug)]
pub struct Resource {
    pub id: i32,
    pub resource_id: i32,
    pub key: String,
    pub rtype: i32,
    pub name: String,
    pub desc: Option<String>,
    pub sort: i32,
    pub path: String,
    pub index: Option<bool>,
    pub menu: Option<bool>,
    pub icon: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Scope {
    pub id: i32,
    pub name: String,
    pub desc: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

