[package]
name = "empty-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2"
async-trait = "0.1"
futures = "0.3"
swagger = { version = "6.2", features = ["serdejson", "server", "client", "tls", "tcp"] }
log = "0.4"
hyper = {version = "0.14", features = ["full"]}
openapi_client={path = "../empty-backend-openapi"}
tokio = { version = "1.21", features = ["full"] }
env_logger = "0.9"

hyper-openssl = { version = "0.9" }
openssl = {version = "0.10" }
tokio-openssl = "0.6"

[dev-dependencies]
tokio = { version = "1.21", features = ["full"] }

