[package]
name = "empty-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
env_logger = "0"
log = "0"
futures = "0"
utoipa = {version = "2", features = ["actix_extras"] }
utoipa-swagger-ui ={version =  "2", features = ["actix-web"] }
diesel = { version = "2", features = ["postgres", "r2d2"] }

